import type { Metadata } from 'next'

import { Header } from '@/components/header'
import { SideMenu } from '@/components/side-menu'
import { Footer } from '@/components/footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='grid grid-areas-layout grid-cols-layout grid-rows-layout h-screen'>
      <Header />
      <SideMenu />
      <main className='grid-in-content p-6 scrollbar-thumb-rounded-full scrollbar-track-rounded-full scrollbar-thin hover:scrollbar-thumb-zinc-800 active:scrollbar-thumb-zinc-700 scrollbar-thumb-zinc-900 scrollbar-track-zinc-950 overflow-y-auto'>
        {children}
      </main>
      <Footer />
    </div>
  )
}
